import './globals.css'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
import { AuthProvider } from '@/auth/context/AuthContext';
import { Suspense } from 'react';
import Loading from './loading';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Suspense fallback = {<Loading />}>
          {children}
          </Suspense>
        </AuthProvider>
        </body>
    </html>
  )
}
